apiVersion: etcd.imliuda.github.io/v1alpha1
kind: EtcdCluster
metadata:
  name: etcdcluster-sample
spec:
  replicas: 3
  version: "3.2.13"
  pod:
    persistentVolumeClaimSpec:
      accessModes: 
      - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
      storageClassName: nfs-client
